### ISSUE TITLE
Cannot find module 'webpack-cli/bin/config-yargs'

### ISSUE THREAD

**Issue by renjiza** [infernojs/inferno-typescript-example#15]
i was follow npm install then npm start but i got this
Error: Cannot find module 'webpack-cli/bin/config-yargs'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (z:\nodejs\inferno-typescript-example\node_modules\webpack-dev-server\bin\webpack-dev-server.js:77:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

**Comment by renjiza** [comment]
fix when update all version of babel plugin
